project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from todo import views

app_name = "todo"

urlpatterns = [
    path("", views.index, name="index"),
    path("todos/", views.todos, name="todos"),
    path("todos/<int:pk>/", views.todo_detail, name="todo-detail"),
    path("todos/<int:pk>/edit", views.todo_edit_form, name="todo-edit-form"),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

class Todo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.pk}: {self.text}"

todo/forms.py
from django.forms import ModelForm
from todo.models import Todo


class TodoForm(ModelForm):
    class Meta:
        model = Todo
        fields = ("text",)

todo/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, QueryDict
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from todo.models import Todo
from todo.forms import TodoForm


def index(request):
    return HttpResponseRedirect(reverse("todo:todos"))


@login_required
def todos(request, pk=None):
    todo_form = None

    if request.method == "POST":
        todo_form = TodoForm(request.POST)
        if todo_form.is_valid():
            todo_form.instance.user = request.user
            todo_form.save()
            todo_form = None

    elif request.method == "DELETE":
        todo = get_object_or_404(Todo, pk=pk)
        if todo.user == request.user:
            todo.delete()
        else:
            raise PermissionDenied("This todo item does not belong to you!")

    if not todo_form:
        todo_form = TodoForm()

    todos = Todo.objects.filter(user=request.user)
    context = {"todos": todos, "todo_form": todo_form}

    return render(request, "todo/index.html", context)


def todo_detail(request, pk=None):
    todo = get_object_or_404(Todo, pk=pk)
    context = {"todo": todo}
    if request.method == "GET":
        return render(request, "todo/todo.html", context)

    elif request.method == "PUT":
        data = QueryDict(request.body).dict()
        form = TodoForm(data, instance=todo)
        if form.is_valid():
            form.save()
            return render(request, "todo/partials/detail.html", context)

        context["form"] = form
        return render(request, "todo/partials/edit-todo-form.html", context)


def todo_edit_form(request, pk=None):
    todo = get_object_or_404(Todo, pk=pk)
    form = TodoForm(instance=todo)
    context = {"todo": todo, "form": form}
    return render(request, "todo/partials/todo-edit-form.html", context)


# def todos_edit(request, pk=)

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script src="https://unpkg.com/htmx.org@1.9.3" integrity="sha384-lVb3Rd/Ca0AxaoZg5sACe8FJKF0tnUgR2Kd7ehUOG5GCcROv5uBIZsOqovBAcWua" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  <title>Todo</title>
</head>
<body hx-boost="true">

  <div class="container mt-4">
    {% block content %}

    {% endblock %}
  </div>

  <script>
    document.body.addEventListener('htmx:configRequest', (event) => {
      event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
  </script>
</body>
</html>

todo/templates/todo/index.html
{% extends 'todo/base.html' %}

{% block content %}

  <h1>Todo</h1>
  <hr>

  <p>
    Welcome, {{ user }}. <a href="{% url 'logout' %}">Log out</a>
  </p>

  <hr>

  <table class="table">
    <thead>
      <tr>
        <td>Id</td>
        <td>Text</td>
      </tr>
    </thead>
    <tbody>
      {% include 'todo/partials/list.html' %}
    </tbody>
  </table>

  <hr>
  <form method="POST" action="{% url 'todo:todos' %}">
    {% csrf_token %}
    {{ todo_form }}
    <button>Submit</button>
  </form>

{% endblock %}

todo/templates/todo/partials/detail.html
<h1>{{ todo.pk }}</h1>
<h2>{{ todo.text }}</h2>

<button 
  hx-get="{% url 'todo:todo-edit-form' todo.pk %}"
  hx-target="#todo-details"
>Edit</button>

todo/templates/todo/partials/list.html
{% for todo in todos %}
  <tr>
    <td>
      <a href="{% url 'todo:todo-detail' todo.pk %}" >
        {{ todo.pk }}
      </a>
    </td>
    <td>
      {{ todo.text }}
    </td>
  </tr>
{% endfor %}

todo/templates/todo/partials/todo-edit-form.html
<form hx-put="{% url 'todo:todo-detail' todo.pk %}" hx-target="#todo-details">
    {% csrf_token %}
    <h1>
      {{ todo.pk }}
    </h1>
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" />
</form>

todo/templates/todo/todo.html
{% extends 'todo/base.html' %}

{% block content %}
<div id="todo-details">
  {% include 'todo/partials/detail.html' %}
</div>
<a href="{% url 'todo:todos' %}">Back</a>
{% endblock %}